
app:
  mysql-server: localhost

spring.jpa.hibernate.ddl-auto: create

spring.datasource:
  url: jdbc:mysql://localhost:3306/invoice
  username: root
  password: sa

spring.jpa.database: mysql

spring.datasource.hikari.initializationFailTimeout: 60000

---
spring.profiles: docker

app:
  mysql-server: database
